### ISSUE TITLE
locate_by_ip needs a new API endpoint to call before 7/1/18

### ISSUE THREAD

**Issue by pwhite00** [pwhite00/misc-scripts#5]
notes : 
# todo: look into ttp://ip-api.com/json as well as updated freegeoip.net changes.
# current api version retires 7/1/18

basically find a new api and or checkout the updated versin of freegeoip.com ( will require an api key and account but still free)

**Comment by freegeoipapp** [comment]
I've setup
https://freegeoip.app

- HTTPS (no HTTP, sorry - it's 2018)
- Rate limit of 15000/hour as before for FREE, guaranteed
- No logs, no analytics - privacy alway in mind
- Continued development for features like bulk lookup and other data sources

no changes needed other than the TLD ;)

**Comment by pwhite00** [comment]
resolved in https://github.com/pwhite00/misc-scripts/pull/6 script re-written in go and using new API

**Comment by pwhite00** [comment]
@freegeoipapp thanks, I'll kill the remaining old instance that runs and move to the new code.
